//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.22 at 04:24:34 PM NZDT 
//


package nz.ac.massey.cs.gpl4jung.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the src.nz.ac.massey.cs.gpl4jung.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: src.nz.ac.massey.cs.gpl4jung.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Query.ExistsNot }
     * 
     */
    public Query.ExistsNot createQueryExistsNot() {
        return new Query.ExistsNot();
    }

    /**
     * Create an instance of {@link Query.Path.Xor }
     * 
     */
    public Query.Path.Xor createQueryPathXor() {
        return new Query.Path.Xor();
    }

    /**
     * Create an instance of {@link Query.Path.Not }
     * 
     */
    public Query.Path.Not createQueryPathNot() {
        return new Query.Path.Not();
    }

    /**
     * Create an instance of {@link Query.Path }
     * 
     */
    public Query.Path createQueryPath() {
        return new Query.Path();
    }

    /**
     * Create an instance of {@link Query.Not.Condition.Attribute }
     * 
     */
    public Query.Not.Condition.Attribute createQueryNotConditionAttribute() {
        return new Query.Not.Condition.Attribute();
    }

    /**
     * Create an instance of {@link Query.Path.Not.And.Property }
     * 
     */
    public Query.Path.Not.And.Property createQueryPathNotAndProperty() {
        return new Query.Path.Not.And.Property();
    }

    /**
     * Create an instance of {@link Query.Path.And.Property }
     * 
     */
    public Query.Path.And.Property createQueryPathAndProperty() {
        return new Query.Path.And.Property();
    }

    /**
     * Create an instance of {@link Query.Path.And }
     * 
     */
    public Query.Path.And createQueryPathAnd() {
        return new Query.Path.And();
    }

    /**
     * Create an instance of {@link Query.Vertex.Or.Condition.Attribute }
     * 
     */
    public Query.Vertex.Or.Condition.Attribute createQueryVertexOrConditionAttribute() {
        return new Query.Vertex.Or.Condition.Attribute();
    }

    /**
     * Create an instance of {@link Query.Vertex.Property }
     * 
     */
    public Query.Vertex.Property createQueryVertexProperty() {
        return new Query.Vertex.Property();
    }

    /**
     * Create an instance of {@link Query.Not }
     * 
     */
    public Query.Not createQueryNot() {
        return new Query.Not();
    }

    /**
     * Create an instance of {@link Query.ExistsNot.Vertex.Property }
     * 
     */
    public Query.ExistsNot.Vertex.Property createQueryExistsNotVertexProperty() {
        return new Query.ExistsNot.Vertex.Property();
    }

    /**
     * Create an instance of {@link Query.Not.Condition }
     * 
     */
    public Query.Not.Condition createQueryNotCondition() {
        return new Query.Not.Condition();
    }

    /**
     * Create an instance of {@link Query.Edge.Property }
     * 
     */
    public Query.Edge.Property createQueryEdgeProperty() {
        return new Query.Edge.Property();
    }

    /**
     * Create an instance of {@link Query.Path.Not.And }
     * 
     */
    public Query.Path.Not.And createQueryPathNotAnd() {
        return new Query.Path.Not.And();
    }

    /**
     * Create an instance of {@link Query.Path.Xor.Property }
     * 
     */
    public Query.Path.Xor.Property createQueryPathXorProperty() {
        return new Query.Path.Xor.Property();
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link Query.Vertex }
     * 
     */
    public Query.Vertex createQueryVertex() {
        return new Query.Vertex();
    }

    /**
     * Create an instance of {@link Query.Vertex.Or.Condition }
     * 
     */
    public Query.Vertex.Or.Condition createQueryVertexOrCondition() {
        return new Query.Vertex.Or.Condition();
    }

    /**
     * Create an instance of {@link Query.Vertex.Or.Property }
     * 
     */
    public Query.Vertex.Or.Property createQueryVertexOrProperty() {
        return new Query.Vertex.Or.Property();
    }

    /**
     * Create an instance of {@link Query.Path.Property }
     * 
     */
    public Query.Path.Property createQueryPathProperty() {
        return new Query.Path.Property();
    }

    /**
     * Create an instance of {@link Query.Vertex.Or }
     * 
     */
    public Query.Vertex.Or createQueryVertexOr() {
        return new Query.Vertex.Or();
    }

    /**
     * Create an instance of {@link Query.Condition }
     * 
     */
    public Query.Condition createQueryCondition() {
        return new Query.Condition();
    }

    /**
     * Create an instance of {@link Query.Edge }
     * 
     */
    public Query.Edge createQueryEdge() {
        return new Query.Edge();
    }

    /**
     * Create an instance of {@link Query.Path.Or }
     * 
     */
    public Query.Path.Or createQueryPathOr() {
        return new Query.Path.Or();
    }

    /**
     * Create an instance of {@link Query.ExistsNot.Vertex }
     * 
     */
    public Query.ExistsNot.Vertex createQueryExistsNotVertex() {
        return new Query.ExistsNot.Vertex();
    }

    /**
     * Create an instance of {@link Query.Condition.Attribute }
     * 
     */
    public Query.Condition.Attribute createQueryConditionAttribute() {
        return new Query.Condition.Attribute();
    }

    /**
     * Create an instance of {@link Query.Graphprocessor }
     * 
     */
    public Query.Graphprocessor createQueryGraphprocessor() {
        return new Query.Graphprocessor();
    }

    /**
     * Create an instance of {@link Query.Path.Or.Property }
     * 
     */
    public Query.Path.Or.Property createQueryPathOrProperty() {
        return new Query.Path.Or.Property();
    }

}
