//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.18 at 08:55:06 PM NZST 
//


package nz.ac.massey.cs.gql4jung.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;choice>
 *           &lt;element name="select" type="{}select"/>
 *           &lt;element name="constraint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="connectedBy" type="{}connectedBy"/>
 *           &lt;element name="groupBy" type="{}groupBy"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "selectOrConstraintOrConnectedBy"
})
@XmlRootElement(name = "motif")
public class Motif {

    @XmlElements({
        @XmlElement(name = "groupBy", type = GroupBy.class),
        @XmlElement(name = "constraint", type = String.class),
        @XmlElement(name = "connectedBy", type = ConnectedBy.class),
        @XmlElement(name = "select", type = Select.class)
    })
    protected List<Object> selectOrConstraintOrConnectedBy;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the selectOrConstraintOrConnectedBy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectOrConstraintOrConnectedBy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectOrConstraintOrConnectedBy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroupBy }
     * {@link String }
     * {@link ConnectedBy }
     * {@link Select }
     * 
     * 
     */
    public List<Object> getSelectOrConstraintOrConnectedBy() {
        if (selectOrConstraintOrConnectedBy == null) {
            selectOrConstraintOrConnectedBy = new ArrayList<Object>();
        }
        return this.selectOrConstraintOrConnectedBy;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
